//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockBoxControl.Blazor.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LockBoxControl.Blazor.Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an Arduino.
        /// </summary>
        public static string AddArduino {
            get {
                return ResourceManager.GetString("AddArduino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arduino&apos;s Name.
        /// </summary>
        public static string ArduinoName {
            get {
                return ResourceManager.GetString("ArduinoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Letter.
        /// </summary>
        public static string CommandLetter {
            get {
                return ResourceManager.GetString("CommandLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Name.
        /// </summary>
        public static string CommandName {
            get {
                return ResourceManager.GetString("CommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Completed On.
        /// </summary>
        public static string CompletedOn {
            get {
                return ResourceManager.GetString("CompletedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New {0}.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no entity associated with this add button dialog for type {0}.
        /// </summary>
        public static string EntityIsNull {
            get {
                return ResourceManager.GetString("EntityIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create {0}.
        /// </summary>
        public static string FailedCreate {
            get {
                return ResourceManager.GetString("FailedCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update {0} with Id = {1}. Error: {2}.
        /// </summary>
        public static string FailedUpdate {
            get {
                return ResourceManager.GetString("FailedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled?.
        /// </summary>
        public static string IsEnabled {
            get {
                return ResourceManager.GetString("IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address.
        /// </summary>
        public static string MacAddress {
            get {
                return ResourceManager.GetString("MacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Name.
        /// </summary>
        public static string PortName {
            get {
                return ResourceManager.GetString("PortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested On.
        /// </summary>
        public static string RequestedOn {
            get {
                return ResourceManager.GetString("RequestedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Form.
        /// </summary>
        public static string ResetForm {
            get {
                return ResourceManager.GetString("ResetForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succes.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully created {0} with Id = {1}.
        /// </summary>
        public static string SuccessCreate {
            get {
                return ResourceManager.GetString("SuccessCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully updated {0} with Id = {1}.
        /// </summary>
        public static string SuccessUpdate {
            get {
                return ResourceManager.GetString("SuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
    }
}
