using LockboxControl.Core.Models.SerialDTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LockboxControl.Core.Models.ApiDTO
{
    public class ArduinoCommandStatus
    {
        public bool IsSuccess { get; set; }
        public string? Status { get; set; }
        public string? ErrorMessage { get; set; }
        public long ArduinoId { get; set; }
        /// <summary>
        /// Unique Id that links the request. It's generated by the server and fed to the arduino and returned to the caller for tracking the command. Useful for long running commands.
        /// </summary>
        public Guid RequestId { get; set; }

        public static ArduinoCommandStatus FromSerialCommandStatus(SerialCommandStatus? serialCommandStatus, long arduinoId)
        {
            return new ArduinoCommandStatus
            {
                ArduinoId = arduinoId,
                ErrorMessage = serialCommandStatus?.ErrorMessage,
                IsSuccess = serialCommandStatus?.IsOk ?? false,
                RequestId = serialCommandStatus?.RequestId ?? Guid.Empty
            };
        }
    }
}
